name: Publish to npm on Main

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14 # You can adjust the Node.js version as needed

            - name: Install dependencies
              run: npm install

            - name: Build package (if needed)
              run: npm build # Replace with your build command if necessary

            - name: Publish to npm
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
